- hosts: localhost
  remote_user: root
  vars:
    debug_params:
      msg: "hello there"
  tasks:

  - name: install node.js
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - nodejs
  
  - name: npm
    shell: cd /root && rm -rf /root/npm && git clone https://github.com/npm/npm && cd npm && make install

  - name: npm
    shell: cd /root && rm -rf /root/osmo-GUI && git clone https://github.com/osmo-GUI

  - name: intall jquery and socket.io
    shell: cd osmo-GUI && npm install --save jquery socket.io


